spring:
  application:
    name: BloomBoard
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bloomboard}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    ignore-migration-patterns: "*:*"

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

server:
  port: ${PORT:8080}
