spring:
  application:
    name: BloomBoard
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 10000
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    ignore-migration-patterns: "*:*"

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

server:
  port: ${PORT:8080}
